version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: snappfood
      POSTGRES_USER: snappfood
      POSTGRES_PASSWORD: snappfood
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI port

  snappfood_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snappfood_service
    restart: always
    environment:
      PORT: 3000
      POSTGRESQL_DATABASE: "host=postgres user=snappfood password=snappfood dbname=snappfood port=5432 sslmode=disable"
      RABBITMQ_CONNECTION: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
